name: Tag

on:
  workflow_call:
    outputs:
      tag:
        description: "Created tag"
        value: ${{ jobs.create-tag.outputs.tag }}

concurrency:
  group: "${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}"

jobs:
  tag:
    permissions: write-all
    name: 🏷️ tag patch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: New tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Output tag
        run: echo "Created tag ${{ steps.create_tag.outputs.new_tag }}"
