name: "Deploy Infra"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  IMAGE_NAME: 'sample_app'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'sa-east-1'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Deploy CDK Stack
      env:
        IMAGE_TAG: ${{ inputs.tag }}
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
      run: |
        cd infra
        npm ci
        npx cdk bootstrap --require-approval never
        npx cdk deploy InfraStack --require-approval never --parameters repositoryName=${IMAGE_NAME} --parameters imageTag=${IMAGE_TAG}
